name: Checking if an artifact produced by another workflow can be used in some other(no).

on:
  workflow_dispatch:

jobs:
  # Added to make this work.
  producer-artifact:
    name: Produce the nginx image tar artifact.
    runs-on: ubuntu-latest
    steps:
      - run: |
          docker save -o alpine-nginx.tar docker.io/library/nginx:1.31-alpine
      - uses: actions/upload-artifact@v4
        with:
          name: container-tar
          path: alpine-nginx.tar

  trivy-scan:
    name: Trivy image scanning on a tar ball.
    needs: producer-artifact
    runs-on: ubuntu-latest
    outputs:
      trivy-result: ${{ steps.scanning.outputs.trivy-result }}
    container:
      image: aquasec/trivy
    steps:
      - name: Download the alpine image tarball.
        uses: actions/download-artifact@v4
        with:
          name: container-tar
      - name: Image testing
        id: scanning
        run: |
          trivy image --input alpine-nginx.tar --format json >> "$GITHUB_OUTPUT"

  output-verification:
    name: Parsing the json output using jq.
    runs-on: ubuntu-latest
    needs: trivy-scan
    steps:
      - name: Parse the trivy scan result using jq and print the lines in the output.
        run: |
          echo "${{ needs.trivy-scan.outputs.trivy-result }}" | jq
          echo "${{ needs.trivy-scan.outputs.trivy-result }}" | wc -l
