name: Workflows form a DAG.
on:
  workflow_dispatch:
    inputs:
      to-greet:
        description: Who to greet in log
        required: false
        default: World
        type: string

jobs:
  hello-inline-bash:
    runs-on: ubuntu-22.04
    steps:
     - run: |
        echo "Hello, world"
        echo "This job must complete before the hello-world-javascript-action proceeds"

  hello-inline-python:
    runs-on: ubuntu-22.04
    steps:
     - run: |
        print("Hello, world")
        print("This runs parallely")
       shell: python

  hello-action:
    runs-on: ubuntu-22.04
    needs: [hello-inline-bash]
    steps:
     - name: Hello, using github hello action.
       uses: actions/hello-world-javascript-action@main
       with:
        who-to-greet: ${{ inputs.to-greet }}
