name: Secrets and Variables

on:
  workflow_dispatch:

jobs:
  staging-environment:
    runs-on: ubuntu-latest
    environment: staging
    env:
      STAGING_ENV_SECRET: ${{ secrets.STAGING_ENV_SECRET }}
      STAGING_ENV_VAR: ${{ vars.STAGING_ENV_VAR }}
      REPO_ENV_SECRET: ${{ secrets.REPO_SECRET }}
      REPO_ENV_VAR: ${{ vars.REPO_ENV_VAR }}
    steps:
      - name: Expose both secrets and vars in the staging environment.
        run: |
          echo "STAGING_ENV_SECRET: ${{ secrets.STAGING_ENV_SECRET }}"
          echo "STAGING_ENV_VAR: ${{ vars.STAGING_ENV_VAR }}"

          echo "Repostiory secret: $REPO_ENV_SECRET"
          echo "Repostiory var: $REPO_ENV_VAR"
  repo-clone-secret:
    runs-on: ubuntu-22.04
    steps:
      - name: Repo secret with the same name as a staging env secret.
        run: |
          echo "STAGING_ENV_SECRET in the second job: ${{ secrets.STAGING_ENV_SECRET }}"
